-- V4__add_active_status.sql

-- Добавляем колонку с дефолтным значением true
ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE companies ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE vacancies ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE resume_reactions ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE interviews ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE resume ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
